### ISSUE TITLE
Usage unknwon

### ISSUE THREAD

**Issue by Binozo** [adaasch/AC-hack#2]
Hello there 👋

I am very interested into this project and hacking my tuya powered air conditioner after all.

I am having a hard time to get things started. Can you give me a hint how I have to proceed to get those serial commands into my tuya board? Do I have to connect an seperate esp32 board to the tuya board using UART? 

Thanks in advance
Greetings from Germany 🍻

**Comment by adaasch** [comment]
Basically you flash Tasmota on the tuya module of the A/C: https://tasmota.github.io/docs/Getting-Started.
After that you can send the serial commands over mqtt to the A/C or you use the mqtt bridge to get a more convenient API:  https://github.com/adaasch/AC-hack/issues/1#issuecomment-2031340282

**Comment by Binozo** [comment]
Thanks!
